export const officers = [
  { OfficerID: 1, Name: 'Detective Nina Rao', Rank: 'Detective', Department: 'Homicide' },
  { OfficerID: 2, Name: 'Inspector Arjun Mehta', Rank: 'Inspector', Department: 'Cyber Crime' },
  { OfficerID: 3, Name: 'Sub-Inspector Kavya Nair', Rank: 'Sub-Inspector', Department: 'Narcotics' },
  { OfficerID: 4, Name: 'Sergeant Rahul Singh', Rank: 'Sergeant', Department: 'Traffic' },
  { OfficerID: 5, Name: 'Constable Priya Sharma', Rank: 'Constable', Department: 'Patrol' },
  { OfficerID: 6, Name: 'Detective Anil Kumar', Rank: 'Detective', Department: 'Fraud' },
  { OfficerID: 7, Name: 'Inspector Meera Joshi', Rank: 'Inspector', Department: 'Cyber Crime' },
  { OfficerID: 8, Name: 'Sub-Inspector Ramesh Patel', Rank: 'Sub-Inspector', Department: 'Narcotics' },
  { OfficerID: 9, Name: 'Sergeant Sunita Verma', Rank: 'Sergeant', Department: 'Homicide' },
  { OfficerID: 10, Name: 'Constable Vikram Desai', Rank: 'Constable', Department: 'Patrol' },
  { OfficerID: 11, Name: 'Detective Suresh Nair', Rank: 'Detective', Department: 'Fraud' },
  { OfficerID: 12, Name: 'Inspector Kavita Rao', Rank: 'Inspector', Department: 'Traffic' },
  { OfficerID: 13, Name: 'Sub-Inspector Ajay Singh', Rank: 'Sub-Inspector', Department: 'Cyber Crime' },
  { OfficerID: 14, Name: 'Sergeant Neha Gupta', Rank: 'Sergeant', Department: 'Narcotics' },
  { OfficerID: 15, Name: 'Constable Rohit Sharma', Rank: 'Constable', Department: 'Patrol' },
  { OfficerID: 16, Name: 'Detective Anjali Mehta', Rank: 'Detective', Department: 'Homicide' },
  { OfficerID: 17, Name: 'Inspector Rajesh Kumar', Rank: 'Inspector', Department: 'Fraud' },
  { OfficerID: 18, Name: 'Sub-Inspector Pooja Singh', Rank: 'Sub-Inspector', Department: 'Traffic' },
  { OfficerID: 19, Name: 'Sergeant Manoj Patel', Rank: 'Sergeant', Department: 'Cyber Crime' },
  { OfficerID: 20, Name: 'Constable Sneha Verma', Rank: 'Constable', Department: 'Patrol' },
  { OfficerID: 21, Name: 'Detective Vikram Joshi', Rank: 'Detective', Department: 'Narcotics' },
  { OfficerID: 22, Name: 'Inspector Ritu Sharma', Rank: 'Inspector', Department: 'Homicide' },
  { OfficerID: 23, Name: 'Sub-Inspector Amit Desai', Rank: 'Sub-Inspector', Department: 'Fraud' },
  { OfficerID: 24, Name: 'Sergeant Kavya Nair', Rank: 'Sergeant', Department: 'Traffic' },
  { OfficerID: 25, Name: 'Constable Rahul Singh', Rank: 'Constable', Department: 'Patrol' },
];

export const cases = [
  { CaseID: 1, Title: 'Bank Robbery', Status: 'Closed', StartDate: '2024-01-10', EndDate: '2024-02-15', LeadOfficerID: 1 },
  { CaseID: 2, Title: 'Online Fraud', Status: 'Under Investigation', StartDate: '2024-04-05', EndDate: null, LeadOfficerID: 2 },
  { CaseID: 3, Title: 'Drug Bust', Status: 'Open', StartDate: '2025-05-01', EndDate: null, LeadOfficerID: 3 },
  { CaseID: 4, Title: 'Cyber Attack', Status: 'Under Investigation', StartDate: '2024-06-10', EndDate: null, LeadOfficerID: 7 },
  { CaseID: 5, Title: 'Homicide Case', Status: 'Closed', StartDate: '2023-12-01', EndDate: '2024-01-20', LeadOfficerID: 9 },
  { CaseID: 6, Title: 'Traffic Violation', Status: 'Open', StartDate: '2025-03-15', EndDate: null, LeadOfficerID: 12 },
  { CaseID: 7, Title: 'Narcotics Raid', Status: 'Closed', StartDate: '2024-02-20', EndDate: '2024-03-30', LeadOfficerID: 14 },
  { CaseID: 8, Title: 'Fraud Investigation', Status: 'Under Investigation', StartDate: '2024-05-05', EndDate: null, LeadOfficerID: 6 },
  { CaseID: 9, Title: 'Patrol Duty', Status: 'Open', StartDate: '2025-01-10', EndDate: null, LeadOfficerID: 20 },
  { CaseID: 10, Title: 'Cyber Crime', Status: 'Closed', StartDate: '2023-11-15', EndDate: '2024-01-05', LeadOfficerID: 19 },
  { CaseID: 11, Title: 'Bank Heist', Status: 'Under Investigation', StartDate: '2024-07-01', EndDate: null, LeadOfficerID: 21 },
  { CaseID: 12, Title: 'Identity Theft', Status: 'Open', StartDate: '2025-04-10', EndDate: null, LeadOfficerID: 22 },
  { CaseID: 13, Title: 'Drug Trafficking', Status: 'Closed', StartDate: '2024-03-05', EndDate: '2024-04-15', LeadOfficerID: 23 },
  { CaseID: 14, Title: 'Traffic Accident', Status: 'Under Investigation', StartDate: '2024-08-20', EndDate: null, LeadOfficerID: 24 },
  { CaseID: 15, Title: 'Patrol Operation', Status: 'Open', StartDate: '2025-02-01', EndDate: null, LeadOfficerID: 25 },
  { CaseID: 16, Title: 'Cyber Fraud', Status: 'Closed', StartDate: '2023-10-10', EndDate: '2023-11-20', LeadOfficerID: 7 },
  { CaseID: 17, Title: 'Homicide Investigation', Status: 'Under Investigation', StartDate: '2024-09-15', EndDate: null, LeadOfficerID: 9 },
  { CaseID: 18, Title: 'Narcotics Smuggling', Status: 'Open', StartDate: '2025-06-05', EndDate: null, LeadOfficerID: 14 },
  { CaseID: 19, Title: 'Fraud Case', Status: 'Closed', StartDate: '2024-01-25', EndDate: '2024-03-10', LeadOfficerID: 6 },
  { CaseID: 20, Title: 'Traffic Enforcement', Status: 'Under Investigation', StartDate: '2024-11-01', EndDate: null, LeadOfficerID: 12 },
  { CaseID: 21, Title: 'Patrol Surveillance', Status: 'Open', StartDate: '2025-05-15', EndDate: null, LeadOfficerID: 20 },
  { CaseID: 22, Title: 'Cyber Security', Status: 'Closed', StartDate: '2023-09-05', EndDate: '2023-10-15', LeadOfficerID: 19 },
  { CaseID: 23, Title: 'Bank Fraud', Status: 'Under Investigation', StartDate: '2024-06-20', EndDate: null, LeadOfficerID: 21 },
  { CaseID: 24, Title: 'Identity Theft Investigation', Status: 'Open', StartDate: '2025-07-10', EndDate: null, LeadOfficerID: 22 },
  { CaseID: 25, Title: 'Drug Enforcement', Status: 'Closed', StartDate: '2024-04-01', EndDate: '2024-05-10', LeadOfficerID: 23 },
];

export const suspects = [
  { SuspectID: 1, Name: 'Ravi Sharma', Age: 35, Gender: 'Male', CaseID: 1, Arrested: true },
  { SuspectID: 2, Name: 'Anita Das', Age: 28, Gender: 'Female', CaseID: 2, Arrested: false },
  { SuspectID: 3, Name: 'Kabir Ali', Age: 40, Gender: 'Male', CaseID: 3, Arrested: true },
  { SuspectID: 4, Name: 'Sunita Patel', Age: 32, Gender: 'Female', CaseID: 4, Arrested: false },
  { SuspectID: 5, Name: 'Rajesh Kumar', Age: 45, Gender: 'Male', CaseID: 5, Arrested: true },
  { SuspectID: 6, Name: 'Pooja Singh', Age: 29, Gender: 'Female', CaseID: 6, Arrested: false },
  { SuspectID: 7, Name: 'Vikram Desai', Age: 38, Gender: 'Male', CaseID: 7, Arrested: true },
  { SuspectID: 8, Name: 'Neha Gupta', Age: 27, Gender: 'Female', CaseID: 8, Arrested: false },
  { SuspectID: 9, Name: 'Amit Sharma', Age: 41, Gender: 'Male', CaseID: 9, Arrested: true },
  { SuspectID: 10, Name: 'Kavita Joshi', Age: 34, Gender: 'Female', CaseID: 10, Arrested: false },
  { SuspectID: 11, Name: 'Rohit Verma', Age: 36, Gender: 'Male', CaseID: 11, Arrested: true },
  { SuspectID: 12, Name: 'Sneha Nair', Age: 30, Gender: 'Female', CaseID: 12, Arrested: false },
  { SuspectID: 13, Name: 'Manoj Patel', Age: 39, Gender: 'Male', CaseID: 13, Arrested: true },
  { SuspectID: 14, Name: 'Anjali Mehta', Age: 26, Gender: 'Female', CaseID: 14, Arrested: false },
  { SuspectID: 15, Name: 'Suresh Kumar', Age: 43, Gender: 'Male', CaseID: 15, Arrested: true },
  { SuspectID: 16, Name: 'Kiran Sharma', Age: 31, Gender: 'Female', CaseID: 16, Arrested: false },
  { SuspectID: 17, Name: 'Rajiv Singh', Age: 37, Gender: 'Male', CaseID: 17, Arrested: true },
  { SuspectID: 18, Name: 'Neeta Verma', Age: 29, Gender: 'Female', CaseID: 18, Arrested: false },
  { SuspectID: 19, Name: 'Deepak Joshi', Age: 42, Gender: 'Male', CaseID: 19, Arrested: true },
  { SuspectID: 20, Name: 'Pooja Patel', Age: 28, Gender: 'Female', CaseID: 20, Arrested: false },
  { SuspectID: 21, Name: 'Rakesh Kumar', Age: 35, Gender: 'Male', CaseID: 21, Arrested: true },
  { SuspectID: 22, Name: 'Sunita Singh', Age: 33, Gender: 'Female', CaseID: 22, Arrested: false },
  { SuspectID: 23, Name: 'Vijay Verma', Age: 40, Gender: 'Male', CaseID: 23, Arrested: true },
  { SuspectID: 24, Name: 'Anita Joshi', Age: 27, Gender: 'Female', CaseID: 24, Arrested: false },
  { SuspectID: 25, Name: 'Rohit Sharma', Age: 38, Gender: 'Male', CaseID: 25, Arrested: true },
];

export const evidence = [
  { EvidenceID: 1, Description: 'Security footage from bank', CollectedDate: '2024-01-12', CaseID: 1, UpdatedBy: 1 },
  { EvidenceID: 2, Description: 'IP logs from scam emails', CollectedDate: '2024-04-10', CaseID: 2, UpdatedBy: 2 },
  { EvidenceID: 3, Description: 'Confiscated narcotics', CollectedDate: '2025-05-05', CaseID: 3, UpdatedBy: 3 },
  { EvidenceID: 4, Description: 'Fingerprint analysis report', CollectedDate: '2024-02-20', CaseID: 4, UpdatedBy: 4 },
  { EvidenceID: 5, Description: 'Bank transaction records', CollectedDate: '2024-03-15', CaseID: 5, UpdatedBy: 5 },
  { EvidenceID: 6, Description: 'Surveillance camera footage', CollectedDate: '2024-06-10', CaseID: 6, UpdatedBy: 6 },
  { EvidenceID: 7, Description: 'Email correspondence logs', CollectedDate: '2024-07-05', CaseID: 7, UpdatedBy: 7 },
  { EvidenceID: 8, Description: 'Drug samples collected', CollectedDate: '2025-01-12', CaseID: 8, UpdatedBy: 8 },
  { EvidenceID: 9, Description: 'Witness statements', CollectedDate: '2024-08-20', CaseID: 9, UpdatedBy: 9 },
  { EvidenceID: 10, Description: 'Phone call records', CollectedDate: '2024-09-15', CaseID: 10, UpdatedBy: 10 },
  { EvidenceID: 11, Description: 'Security system logs', CollectedDate: '2024-10-10', CaseID: 11, UpdatedBy: 11 },
  { EvidenceID: 12, Description: 'Forensic lab results', CollectedDate: '2024-11-05', CaseID: 12, UpdatedBy: 12 },
  { EvidenceID: 13, Description: 'Confidential informant reports', CollectedDate: '2025-02-20', CaseID: 13, UpdatedBy: 13 },
  { EvidenceID: 14, Description: 'Vehicle tracking data', CollectedDate: '2025-03-15', CaseID: 14, UpdatedBy: 14 },
  { EvidenceID: 15, Description: 'Bank account statements', CollectedDate: '2025-04-10', CaseID: 15, UpdatedBy: 15 },
  { EvidenceID: 16, Description: 'Digital device analysis', CollectedDate: '2025-05-05', CaseID: 16, UpdatedBy: 16 },
  { EvidenceID: 17, Description: 'Surveillance photos', CollectedDate: '2025-06-01', CaseID: 17, UpdatedBy: 17 },
  { EvidenceID: 18, Description: 'Audio recordings', CollectedDate: '2025-07-10', CaseID: 18, UpdatedBy: 18 },
  { EvidenceID: 19, Description: 'Text message logs', CollectedDate: '2025-08-05', CaseID: 19, UpdatedBy: 19 },
  { EvidenceID: 20, Description: 'Security badges', CollectedDate: '2025-09-01', CaseID: 20, UpdatedBy: 20 },
  { EvidenceID: 21, Description: 'Witness sketches', CollectedDate: '2025-10-10', CaseID: 21, UpdatedBy: 21 },
  { EvidenceID: 22, Description: 'Crime scene photos', CollectedDate: '2025-11-05', CaseID: 22, UpdatedBy: 22 },
  { EvidenceID: 23, Description: 'Financial audit reports', CollectedDate: '2025-12-01', CaseID: 23, UpdatedBy: 23 },
  { EvidenceID: 24, Description: 'Security patrol logs', CollectedDate: '2026-01-15', CaseID: 24, UpdatedBy: 24 },
  { EvidenceID: 25, Description: 'Forensic DNA analysis', CollectedDate: '2026-02-10', CaseID: 25, UpdatedBy: 25 },
];
